[package]
name = "product_contract"
version = "0.1.0"
edition = "2024"
[lib]
path = "lib.rs"
[dependencies]
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
shared_contract = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true }
[lints]
workspace = true
