[package]
name = "warehouse"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
appctx = { workspace = true, features = ["test-utils"] }
approval = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
code_gen = { workspace = true }
db = { workspace = true }
feature = { workspace = true }
inventory_ledger = { workspace = true }
migration = { workspace = true }
rootcause = { workspace = true }
sea-query = { workspace = true }
sea-query-sqlx = { workspace = true }
serde = { workspace = true }
shared_contract = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
validify = { workspace = true }
warehouse_contract = { workspace = true }
web = { workspace = true }

[lints]
workspace = true
