[package]
name = "identity_contract"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
argon2 = { workspace = true }
rootcause = { workspace = true }
serde = { workspace = true }
shared_contract = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
utoipa = { workspace = true }
validify = { workspace = true }

[lints]
workspace = true
