[package]
name = "file_contract"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
chrono = { workspace = true, features = ["clock"] }
imageformat = { workspace = true }
rootcause = { workspace = true }
tempoid = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
