[package]
name = "queue"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[lints]
workspace = true

[features]
default = ["pg"]
pg = []
nats = ["dep:async-nats", "dep:uuid", "dep:bytes", "dep:serde"]

[dependencies]
chrono = { workspace = true, features = ["clock", "std"] }
db = { workspace = true }
futures-util = { workspace = true }
rootcause = { workspace = true }
serde_json = { workspace = true }
shared_contract = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
bytes = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
async-nats = { version = "0.50", optional = true }
uuid = { version = "1.24", features = ["v7"], optional = true }

[dev-dependencies]
migration = { workspace = true }
serde = { workspace = true, features = ["derive"] }
