[package]
name = "audit_contract"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
ipnetwork = { workspace = true }
rootcause = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shared_contract = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }

[lints]
workspace = true
