/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppContentArticlesRouteImport } from './routes/_app/content/articles'
import { Route as AppContentCategoriesRouteImport } from './routes/_app/content/categories'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppSettingsPermissionsRouteImport } from './routes/_app/settings/permissions'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppContentArticlesRoute = AppContentArticlesRouteImport.update({
  id: '/content/articles',
  path: '/content/articles',
  getParentRoute: () => AppRoute,
} as any)
const AppContentCategoriesRoute = AppContentCategoriesRouteImport.update({
  id: '/content/categories',
  path: '/content/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPermissionsRoute = AppSettingsPermissionsRouteImport.update({
  id: '/settings/permissions',
  path: '/settings/permissions',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/users': typeof AppUsersRoute
  '/content/articles': typeof AppContentArticlesRoute
  '/content/categories': typeof AppContentCategoriesRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/permissions': typeof AppSettingsPermissionsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/content/articles': typeof AppContentArticlesRoute
  '/content/categories': typeof AppContentCategoriesRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/permissions': typeof AppSettingsPermissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/content/articles': typeof AppContentArticlesRoute
  '/_app/content/categories': typeof AppContentCategoriesRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/settings/permissions': typeof AppSettingsPermissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/users'
    | '/content/articles'
    | '/content/categories'
    | '/settings/general'
    | '/settings/permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/users'
    | '/'
    | '/content/articles'
    | '/content/categories'
    | '/settings/general'
    | '/settings/permissions'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/profile'
    | '/_app/users'
    | '/_app/'
    | '/_app/content/articles'
    | '/_app/content/categories'
    | '/_app/settings/general'
    | '/_app/settings/permissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/articles': {
      id: '/_app/content/articles'
      path: '/content/articles'
      fullPath: '/content/articles'
      preLoaderRoute: typeof AppContentArticlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/categories': {
      id: '/_app/content/categories'
      path: '/content/categories'
      fullPath: '/content/categories'
      preLoaderRoute: typeof AppContentCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/permissions': {
      id: '/_app/settings/permissions'
      path: '/settings/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AppSettingsPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContentArticlesRoute: typeof AppContentArticlesRoute
  AppContentCategoriesRoute: typeof AppContentCategoriesRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsPermissionsRoute: typeof AppSettingsPermissionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppContentArticlesRoute: AppContentArticlesRoute,
  AppContentCategoriesRoute: AppContentCategoriesRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsPermissionsRoute: AppSettingsPermissionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
