[package]
name = "planning"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
appctx = { workspace = true, features = ["test-utils"] }
axum = { workspace = true }
db = { workspace = true }
item_contract = { workspace = true }
migration = { workspace = true }
module = { workspace = true }
planning_contract = { workspace = true }
rootcause = { workspace = true }
serde = { workspace = true }
shared_contract = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
web = { workspace = true }

[lints]
workspace = true
