[package]
name = "item_contract"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
chrono = { workspace = true }
rootcause = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
shared_contract = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true, features = ["decimal"] }

[lints]
workspace = true
