[package]
name = "web"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
axum = { workspace = true }
axum_typed_multipart = { workspace = true }
shared_contract = { workspace = true }
rootcause = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
validify = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
