[package]
name = "cache"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[lints]
workspace = true

[features]
default = ["pg"]
pg = ["dep:sqlx", "dep:db"]
redb = ["dep:redb"]
redis = ["dep:bb8-redis", "dep:redis"]

[dependencies]
chrono = { workspace = true, features = ["clock", "std"] }
rootcause = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, optional = true }
db = { workspace = true, optional = true }
redb = { version = "4.1", optional = true }
bb8-redis = { version = "0.26", optional = true }
redis = { version = "1.5", features = ["tokio-comp"], optional = true }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
migration = { workspace = true }
testcontainers-modules = { workspace = true, features = ["redis"] }
